/**
 * Le jeu d'essai du banc IA : de VRAIES phrases, chacune avec ce qu'elle
 * veut dire.
 *
 *   - `reel`   : messages de clients relevés dans la base (26/09), étiquetés
 *                à la main ;
 *   - `piege`  : phrases écrites exprès pour faire tomber un système qui
 *                devine au lieu de comprendre (« livre » / « livreur »,
 *                « litre », « un paquet de biscuits », « le livreur est en
 *                retard »…), dont des phrases en haoussa et en zarma.
 *
 * `contexte: true` : la phrase n'a de sens qu'avec la conversation (« Oui »,
 * « Yantala. » en réponse à une question). Comptée à part : un classifieur
 * qui ne voit que la phrase ne peut pas la réussir, un système complet si.
 *
 * Toute erreur vue en production vient s'ajouter ici — c'est ce qui empêche
 * qu'elle revienne.
 */
import type { Intention } from '../../src/ai/jev.js';

export interface Cas {
  texte: string;
  attendu: Intention;
  source: 'reel' | 'piege';
  contexte?: boolean;
  /** Le dernier message de Tovo, pour les phrases à contexte. */
  avant?: string;
  /** Pourquoi c'est un piège, ou ce que la phrase veut dire. */
  note?: string;
}

/** Les actions qui coûtent si on les déclenche à tort. */
export const COUTEUSES = new Set<Intention>(['livreur', 'colis', 'annuler', 'habitude']);

const r = (texte: string, attendu: Intention, extra: Partial<Cas> = {}): Cas =>
  ({ texte, attendu, source: 'reel', ...extra });
const p = (texte: string, attendu: Intention, note: string): Cas =>
  ({ texte, attendu, source: 'piege', note });
const ctx = { contexte: true };

export const JEU: Cas[] = [
  // ── Vrais messages de clients ────────────────────────────────────────
  r('tacos au poulet', 'recherche'),
  r('pizza', 'recherche'),
  r('tacos', 'recherche'),
  r('burger', 'recherche'),
  r('annule ma commande', 'annuler'),
  r("montre moi tout ce qu'il y a", 'envie'),
  r('annule', 'annuler'),
  r('y a t il des écouteurs ?', 'recherche'),
  r('casque audio', 'recherche'),
  r('va plus loin que la distance annoncée', 'recherche', { ...ctx, avant: 'Je ne trouve pas de pommade à moins de 3 km.', note: 'élargir la recherche précédente' }),
  r('je cherche des plats chauds', 'envie'),
  r('Oui', 'social', { ...ctx, avant: 'Avez-vous besoin d’autre chose ?' }),
  r('quels restaurants sont ouverts ?', 'envie'),
  r('je veux voir tous les produits de otakoss', 'boutique'),
  r('va plus loin', 'recherche', { ...ctx, avant: 'Je ne trouve pas d’écouteurs à moins de 3 km.' }),
  r('annule la commande', 'annuler'),
  r('je veux envoyer u colis a un ami', 'colis'),
  r('tacos poulet', 'recherche'),
  r('je veux un tacos', 'recherche'),
  r('je cherche des écouteurs sans fil', 'recherche'),
  r('annulez la commande', 'annuler'),
  r('Merci', 'social'),
  r('peu importe, propose moi le catalogue entier', 'envie'),
  r('y a quoi comme pizza ?', 'recherche'),
  r('j’ai une course', 'livreur'),
  r('je veux envoyer un colis', 'colis'),
  r('plateau, moyen', 'colis', { ...ctx, avant: 'Où faut-il livrer le colis, et quelle est sa taille ?', note: 'destination et taille du colis' }),
  r('de la crème fraîche 😁', 'recherche'),
  r('de la crème fraîche pour les gratins de pomme de terre', 'recherche'),
  r('non , je cherche de la crème fraîche liquide, celle vendue en alimentation.', 'recherche'),
  r('Bon on m’a dit de commander ce qui est disponible, donc je veux du poulet', 'recherche'),
  r('je veux viande haché', 'recherche'),
  r('je cherche de la crème fraîche', 'recherche'),
  r('boulette, à otakoss. un tacos avec la viande boulette dedans', 'recherche'),
  r('tacos aux boulettes viande à otakoss', 'recherche'),
  r('Tacos aux boulettes de viande de chez otakoss', 'recherche'),
  r("otakoss j'ai dit et j'ai parlé d'un takos bien spécifique", 'recherche', ctx),
  r('je cherche un tacos aux boulettes', 'recherche'),
  r('tacos aux boulettes taille M', 'recherche'),
  r('je cherche un tacos poulet chez otakoss', 'recherche'),
  r('montre moi le début de toutes les catégories', 'envie'),
  r('je veux acheter un poulet', 'recherche'),
  r('je veux du poulet', 'recherche'),
  r('quels sont les meilleures vents de ces restaurants ?', 'envie', { ...ctx, note: '« ventes » mal écrit' }),
  r('bobiel', 'recherche', { ...ctx, avant: 'Dans quel quartier cherchez-vous du poulet ?', note: 'un quartier, en réponse' }),
  r('Je veux manger', 'envie'),
  r('Je veux manger un bon tacos', 'recherche'),
  r('Je veux un burger !', 'recherche'),
  r('Bonsoir', 'social'),
  r('Je faim mais je ne sais pas quoi manger', 'envie'),
  r('Un tacos peut être ?', 'recherche'),
  r('Qui est le fondateur de Tovo ?', 'social'),
  r('Je cherche du poulet frit', 'recherche'),
  r('Peu importe le quartier', 'recherche', { ...ctx, avant: 'Dans quel quartier cherchez-vous du poulet ?' }),
  r("Garda d'or", 'boutique', { note: 'Garba d’Or mal écrit' }),
  r("Cherche moi des plats de chez garba d'or", 'boutique'),
  r('Je veux du yaourt', 'recherche'),
  r('Otakoss', 'boutique'),
  r('Otakoss centre aéré', 'boutique'),
  r('Je veux manger du poulet', 'recherche'),
  r('Et tacos ?', 'recherche'),
  r('Bonjour', 'social'),
  r('Envoyer un colis', 'colis'),
  r("J'ai changé d'avis", 'social', ctx),
  r('Un plats a livrer', 'envie'),
  r('Je veux manger du poulet.', 'recherche'),
  r('Mahamadou cissé ? C\'est qui ça ?', 'social'),
  r("D'où tu tiens cette information ?", 'social'),
  r('Je parle de mahamadou cissé', 'social', ctx),
  r('Montre', 'recherche', { note: 'une montre (bracelet)' }),
  r('Il y a des montres quand même ? Quelle que soit la marque ?', 'recherche'),
  r('Boutique ouverte en ce moment sur otakoss', 'boutique'),
  r('Boutique ouverte présentement', 'envie'),
  r("Qu'importe. Une boutique ouverte", 'envie'),
  r('Tu es bête', 'social'),
  r('Avez-vous une autre montre ? Quelle que soit la marque ?', 'recherche'),
  r('Un bracelet ?', 'recherche'),
  r('De la pommade', 'recherche'),
  r('Mais c’est un casque de moto ça', 'social', ctx),
  r('D’accord. Y a t il des restaurants ouverts ?', 'envie'),
  r("J'ai envie de commander un tacos poulet de chez O'Tacos.", 'recherche'),
  r("J'ai envie de commander un restaurant. En fait, j'ai envie de poulet. Qu'est-ce que vous avez comme poulet dans votre catalogue ?", 'recherche'),
  r('Poulet', 'recherche'),
  r('Salut, je voudrais manger du poulet.', 'recherche'),
  r('Je veux manger de la pizza', 'recherche'),
  r('Je vais manger de la viande hachée.', 'recherche'),
  r('Comment une brochette haque-frite haque-poulet.', 'recherche', { note: 'vocal mal transcrit' }),
  r('Je veux du poulet.', 'recherche'),
  r('Dokounou', 'recherche'),
  r('Tu connais ?', 'social', ctx),
  r('Recherche Doukounou', 'recherche'),
  r('C’est qui Sahid ?', 'social'),
  r('Binjour', 'social'),
  r('Comment vas-tu ?', 'social'),
  r('Doukounou tu en as ?', 'recherche'),
  r('Qu’est-ce que vous avez comme montre ?', 'recherche'),
  r('Sur ? Et avez-vous d’autres choses ?', 'envie', ctx),
  r('Je veux faire mes courses', 'envie'),
  r('Je veux commander à manger Je veux un tacos.', 'recherche'),
  r('Je veux envoyer un livreur.', 'livreur'),
  r('Je veux un livreur.', 'livreur'),
  r('Je veux du doukounou', 'recherche'),
  r('Et les tacos ?', 'recherche'),
  r('Appeler un livreur', 'livreur'),
  r('Je veux manger une salade.', 'recherche'),
  r('Je cherche un bon restaurant à Niamey', 'envie'),
  r("Je veux manger du bon l'ukounou. Qu'est-ce que tu me, euh, réserves ? Qu'est-ce que tu me, qu'est-ce qu'il y a comme bon coin pour manger du bon l'ukounou ?", 'recherche', { note: 'doukounou mal transcrit' }),
  r('Je veux manger du bon doukounou, du bon doukounou.', 'recherche'),
  r('Quelles sont les boutiques ouvertes présentement ?', 'envie'),
  r('Je veux du bon à checker.', 'recherche', { note: 'attiéké mal transcrit' }),
  r('Attiéké', 'recherche'),
  r("Je veux manger à Garbador. Qu'est-ce que Garbador a comme produit ?", 'boutique'),
  r('Je veux manger du poisson braisé.', 'recherche'),
  r('Où est mon panier ?', 'designe', { note: 'voir son panier' }),
  r('Je veux commander de la viande chez CHOS.', 'recherche'),
  r('Je veux commander de la viande, de la bouffe de street.', 'recherche'),
  r('Je veux commander des tacos.', 'recherche'),
  r('Je veux un sandwich tacos.', 'recherche'),
  r('Je veux commander des couches pour bébé.', 'recherche'),
  r('Je veux commander du doukounou.', 'recherche'),
  r('Je veux commander du ATTIEKE FONFON.', 'recherche'),
  r('Je voudrais un livreur.', 'livreur'),
  r('Je veux manger chawarma.', 'recherche'),
  r('Je veux des glaces, je veux aller au glacier.', 'recherche'),
  r('Je veux des glaces.', 'recherche'),
  r('Je veux du poulet frais.', 'recherche'),
  r('Je voudrais payer une chemise de couleur blanche pour la relique.', 'recherche'),
  r('Je voudrais une chemise.', 'recherche'),
  r('Une chemise de couleur blanche.', 'recherche'),
  r('Je voudrais une femme.', 'social', { note: 'hors sujet' }),
  r('Une femme à marier, pas un parfum.', 'social'),
  r('Je voudrais une femme à marier.', 'social'),
  r('Je veux du lait.', 'recherche'),
  r('Je voudrais des œufs.', 'recherche'),
  r('Je veux manger hamburger.', 'recherche'),
  r('Je veux manger du manuku.', 'recherche', { note: 'doukounou mal transcrit' }),
  r('Je veux un autre livreur', 'livreur'),
  r('Je veux un livreur', 'livreur'),
  r('Livreur', 'livreur'),
  r('AFC', 'boutique'),
  r('Restaurant afc', 'boutique'),
  r('AFC restaurant', 'boutique'),
  r('Annule toutes mes commandes en cours', 'annuler'),
  r('Ah ouais. Bonsoir. Je voudrais commander.', 'envie'),
  r('Un Boba', 'recherche'),
  r('Bonsoir.', 'social'),
  r('Je voudrais un livre.', 'recherche', { note: 'un LIVRE, pas un livreur' }),
  r('Je voudrais un autre livre.', 'recherche', { note: 'un LIVRE, pas un livreur' }),
  r('Je voudrais un autre livret pour récupérer un colis.', 'livreur', { note: '« livret » pour « livreur »' }),
  r('Yantala.', 'livreur', { ...ctx, avant: 'Où le livreur doit-il récupérer le colis ?', note: 'où récupérer le colis, en réponse' }),
  r('Je viens livrer.', 'social', { note: 'ambigu : un livreur qui se présente' }),
  r('Je manger aussi', 'envie'),
  r('Je cherche un livre', 'recherche', { note: 'un LIVRE, pas un livreur' }),
  r('Je cherche un livre euh', 'recherche', { note: 'un LIVRE, pas un livreur' }),

  // ── Pièges ───────────────────────────────────────────────────────────
  p('Je cherche un livre de cuisine', 'recherche', 'livre ≠ livreur'),
  p('Vous avez des livres pour enfants ?', 'recherche', 'livre ≠ livreur'),
  p('un livre de coran', 'recherche', 'livre ≠ livreur'),
  p('Il me faut un litre d’huile', 'recherche', 'litre : une mesure, pas un produit'),
  p('deux litres de lait', 'recherche', 'litre : une mesure'),
  p('Je veux un paquet de biscuits', 'recherche', 'paquet : un emballage, pas un colis'),
  p('un colis de riz de 25 kg', 'recherche', 'un sac de riz, pas un envoi'),
  p('Il arrive quand le livreur ?', 'suivi', 'contient « livreur » mais c’est du suivi'),
  p('Le livreur est en retard', 'suivi', 'contient « livreur » mais c’est du suivi'),
  p('Mon livreur ne répond pas', 'suivi', 'contient « livreur » mais c’est du suivi'),
  p('Je veux devenir livreur', 'social', 'un emploi, pas une course'),
  p('Comment travailler comme livreur chez vous ?', 'social', 'un emploi, pas une course'),
  p('Le livreur a été très gentil merci', 'social', 'un remerciement'),
  p('Envoie-moi un coursier', 'livreur', 'vraie demande'),
  p('Il me faut une moto tout de suite', 'livreur', 'vraie demande, sans le mot livreur'),
  p('Viens chercher un sac chez moi et dépose-le à Koira Kano', 'colis', 'vraie demande de course'),
  p('Récupère mon téléphone chez Moussa au Plateau', 'colis', 'aller chercher et apporter'),
  p('Envoie ce document à ma sœur à Lazaret', 'colis', 'vraie demande'),
  p('Où en est ma commande ?', 'suivi', 'suivi'),
  p('C’est encore loin ?', 'suivi', 'suivi, sans mot-clé'),
  p('Annule le coca', 'designe', 'retirer un article, pas annuler la commande'),
  p('Enlève le deuxième', 'designe', 'désigne un article affiché'),
  p('Je prends le deuxième', 'designe', 'désigne un article affiché'),
  p('Le moins cher', 'designe', 'désigne un article affiché'),
  p('Comme d’habitude', 'habitude', 'refaire une commande'),
  p('La même chose que la dernière fois', 'habitude', 'refaire une commande'),
  p('Je ne veux plus rien, laisse tomber ma commande', 'annuler', 'annulation sans le mot'),
  p('Je veux commander chez AFC', 'boutique', 'une boutique nommée'),
  p('C’est ouvert chez Boba ?', 'boutique', 'une boutique nommée'),
  p('Ina son abinci', 'envie', 'haoussa : je veux de la nourriture'),
  p('Ina son kilishi', 'recherche', 'haoussa : je veux du kilishi'),
  p('Ay ga baa ŋwaari', 'envie', 'zarma : je veux de la nourriture'),
  p('fura da nono', 'recherche', 'boisson (haoussa)'),
  p('Donne-moi du kopto', 'recherche', 'plat local'),
  p('Envoie du riz chez ma mère à Talladjé', 'recherche', 'une commande livrée à quelqu’un, pas un colis'),
  p('Tu peux me livrer un poulet braisé ?', 'recherche', '« livrer » mais c’est un produit'),
  p('Livre-moi deux pizzas', 'recherche', '« livre-moi » : un verbe, et des pizzas'),
  p('Bonjour Tovo, ça va ?', 'social', 'salutation'),
  p('Merci beaucoup, c’était rapide', 'social', 'remerciement'),
];
